[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"

[[services]]
name = "perfscope-backend"
source = "backend"

[[services]]
name = "perfscope-postgres"
source = "postgres:15"